- .github/workflows/Publish.yml
Lets try this again. This time with better yaml!
> fix: 🐛 Only one hyphen allowed per github action step

- package.json
> fix: 🐛 Fixes package.json repo url

- SQFormDocs/docs/installation.mdx
> docs: ✏️ Use material ui pickers alpha version

- notes/SQForm.md
- src/components/SQForm/SQFormCheckboxGroup.js
- src/components/SQForm/SQFormCheckboxGroupItem.js
- src/index.js
- stories/SQForm.stories.js
SQFormCheckboxGroup and -Item comps enable an 'inclusion list' UX to
add/remove items from a larger list of options via checkbox, with an
optional 'select all' functionality built in.
[Loom demo](https://www.loom.com/share/021e1f7fed42443181b4285aa81cdf3f)
> feat: 🎸 add SQFormCheckboxGroup and SQFormCheckboxGroupItem

- notes/SQForm.md
- src/components/SQForm/SQFormMultiSelect.js
- src/index.js
- stories/SQForm.stories.js
A new multiselect field for SQForm, equipped with Select All capability
https://www.loom.com/share/f1c1a91da7a745acbf25c646ae35018c
✅ Closes: SSC-82
> feat: 🎸 SQForm MultiSelect

- src/components/SQForm/SQFormMultiSelect.js
Fixed a list item in multi select to use the label instead of value
✅ Closes: SSC-82
> fix: 🐛 Fixed a list item label

- src/components/SQForm/SQFormMultiSelect.js
- stories/SQForm.stories.js
A value render was built under assumption label and value were same,
which was a bad assumption.
✅ Closes: SSC-82
> fix: 🐛 Fixed a multi select value render

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
- stories/SQFormDialogStepper.stories.js
✅ Closes: #52
Updated a handful of UX/UI related items in the stepper component after getting feedback from UX Chris Nemeth.  
* removed navigation arrows
* updated current step font color
* updated examples in storybook
* Fixed the width of the stepper steps
Loom: https://www.loom.com/share/d2e7c6767cf74dbaaf4edf3f784daa8a
> feat: 🎸 Updated stepper component step styling and removed arrows SSC-108

- src/components/SQFormDialog/SQFormDialog.js
- src/components/SQFormDialog/SQFormDialogInner.js
✅ Closes: #60 
Added Are you Sure? Dialog Alert in SQFormDialog
AYS modal will be open if the form is dirty otherwise dialog will be close upon clicking the cancel button.
here is an updated  loom video
https://www.loom.com/share/c15d212716e9415eb2af9bc20e7a4c4a
> Added Are you Sure? Dialog in SQFormDialog component

- src/components/LoadingIcon/LoadingIcon.js
- src/components/LoadingSpinner/LoadingSpinner.js
- src/components/SQForm/SQForm.js
- src/components/SQForm/SQFormAsyncAutocomplete.js
- src/components/SQForm/SQFormIconButton.js
- src/components/SQForm/SQFormResetButtonWithConfirmation.js
- src/components/SQForm/SQFormResetInitialValuesButton.js
- src/components/SQForm/SQFormTextarea.js
- src/components/SQFormDialog/SQFormDialog.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
Added missing proptype documentation including missing props, default
values, and descriptions.
✅ Closes: #95
No loom as no functionality changed. 👍 for documentation! 🎉
> fix: 🐛 Added missing proptype documentation

- src/components/SQForm/SQFormRadioButtonGroup.js
- src/components/SQForm/SQFormRadioButtonGroupItem.js
- src/index.js
- stories/SQForm.stories.js
- stories/SQFormRadioGroup.stories.js
Added SQFormRadioButtonGroup component to allow for a radio button input
within the context of SQForm
✅ Closes: #64
Checkout this mind blowing loom: https://www.loom.com/share/3bc2d0ed03e44fd19ef52bbe39b88381
> feat: 🎸 Added SQFormRadioButtonGroup component

- notes/SQForm.md
- src/components/SQForm/SQFormCheckboxGroup.js
- src/components/SQForm/SQFormCheckboxGroupItem.js
- src/components/SQForm/SQFormInclusionList.js
- src/components/SQForm/SQFormInclusionListItem.js
- src/index.js
- stories/SQForm.stories.js
- stories/SQFormDialogStepper.stories.js
Renamed SQFormCheckboxGroup(Item) to SQFormInclusionList(Item) and readd
SQFormCheckboxGroup(Item) to creage a checkbox group to be used within
SQForm and other form elements
BREAKING CHANGE: 🧨 Rename SQFormCheckboxGroup(Item) to SQFormInclusionList(Item)
Diff is pretty bad since we reused a file.
✅ Closes: #101
Look at this loom! https://www.loom.com/share/0373e3e4221b4a04a60c5c1568477410
> feat: 🎸 Rename SQFormCheckboxGroup and replace it

- src/components/SQForm/SQFormDropdown.js
feat: 🎸 In this feature we can disable dropdown option
In this feature we can disable SQFormdropdown option specifically by
providing isDisable value
✅ Closes: 118
screenshot:
> feat: 🎸added disable option in menuItem for disabling dropdown option

- README.md
Updated the readme to include how to handle breaking changes
> docs: ✏️ Updated readme to include a section on breaking changes

- README.md
> docs: ✏️ add description for using chore commit type

- SQFormDocs/docs/common_issues.mdx
- SQFormDocs/package-lock.json
- SQFormDocs/sidebars.js
- package-lock.json
- src/components/SQForm/SQFormDropdown.js
- src/components/SQForm/SQFormMultiSelect.js
- src/utils/consoleWarnings.js
Gracefully handle unexpected initialValues on SQForm and unexpected
children passed to SQFormDropdown and SQFormMultiSelect. A warning is
now displayed with information to help resolve the issues. A new "Common
Issues" doc page has been added as well.
**I took a lot of liberties here as a first stab. Let me know if you've envisioned something else.**
✅ Closes: #124
Loom: https://www.loom.com/share/fb27d19d58a24d13a663d6da5c4e2d69
> fix: 🐛 Gracefully handle unexpeced initialValues and children

- src/index.js
- src/utils/index.js
- stories/SQForm.stories.js
I'm not very familiar with exporting things for use in a component library, so please let me know if there's a better to do it
✅ Closes: #140
> fix: 🐛 correctly export MASKS from utils

- package-lock.json
- package.json
- src/components/SQForm/SQForm.js
- src/components/SQForm/SQFormButton.js
- src/components/SQForm/SQFormIconButton.js
- src/components/SQForm/useFormButton.js
Add [debounced callback](https://www.npmjs.com/package/use-debounce) to the `SQForm` onSubmit and `SQFormButton`/`SQFormIconButton` onClick. For the buttons the debounce is handled within `useFormButton`.
The timer is set to 500ms, as discussed in the issue, and the config is set to allow leading calls, but not trailing. Meaning the event will be fired immediately upon initiation, then can't be fired again until the timer has completed.
Loom: https://www.loom.com/share/e2522c52a8b9422b9c969359a06359c2
✅ Closes: #123
> feat: 🎸 add debounce to SQForm onSubmit and buttons onClick

- package.json
With this we can use `test` as the commit flag in `npm run commit` when
adding tests
> chore: 🤖 add `test` to commitlint options

- stories/SQFormDropdown.stories.js
- stories/SQFormMultiSelect.stories.js
ref: #161 
https://www.loom.com/share/22a09ac9b7f04c1eaa889abe29edd192
> chore: 🤖 add dropdown and multiselect component stories

- stories/SQFormDatePicker.stories.js
- stories/SQFormDatePickerWithCalendarInputOnly.stories.js
- stories/SQFormDateTimePicker.stories.js
- stories/SQFormDropdown.stories.js
- stories/SQFormMultiSelect.stories.js
- stories/components/SQFormStoryWrapper.js
Update DatePicker stories to use new Storybook format to auto-generate
docs
Also added `SQFormStoryWrapper` component to be used in place of `SQForm` in stories. It takes the basic props a component story would need and handles the onSubmit so that doesn't have to be set up with storybook actions for each story
https://www.loom.com/share/b7ea539287e5431aa7e10a315b1eafcd
Update: Refactored `SQFormStoryWrapper` to include a checkmark icon button for submitting because some components don't have a way to submit via keyboard. Also updated `SQFormDropdown/MultiSelect` to use wrapper
✅ Closes: #186
> docs: ✏️ update DatePicker stories

- stories/components/SQFormStoryWrapper.js
Improvements to the `SQFormStoryWrapper` submit handler and how the submitted data is displayed.
Late night loom rambling: https://www.loom.com/share/9fdfd6922e5447af93442869afd28ad3
✅ Closes: #196
> docs: ✏️ improve SQFormStoryWrapper submit handler

- stories/SQFormButton.stories.js
- stories/SQFormIconButton.stories.js
Stories for SQFormButton and SQFormIconButton, each has a story for the
defaultstate of the component and a story with a TextField for demoing
the functionality of some props
https://www.loom.com/share/b30db32cf3224c00ac822607addab46d
✅ Closes: #200
> docs: ✏️ add stories for Button and IconButton

- stories/SQFormAsyncAutocomplete.stories.js
- stories/SQFormAutocomplete.stories.js
https://www.loom.com/share/9c6bce8c682b4564b765b52b453f7e69
✅ Closes: #206
> docs: ✏️ add stories for Autocomplete and AsyncAutocomplete

- stories/SQFormDialog.stories.js
Cleaned up and refactored stories to use new storybook syntax/features
https://www.loom.com/share/3a155944641c43deac941579ca89b4fa
✅ Closes: #209
> docs: ✏️ refactor `SQFormDialog` stories

- src/components/SQForm/SQFormCheckboxGroup.js
- src/components/SQForm/SQFormDatePickerWithCalendarInputOnly.js
- src/components/SQForm/SQFormInclusionList.js
- src/components/SQForm/SQFormMultiSelect.js
- src/components/SQForm/SQFormRadioButtonGroup.js
- src/components/SQFormDialog/SQFormDialogInner.js
✅ Closes: #233
I noticed during our build process we had 6 circular dependencies 😨 
This PR fixes the circular dependencies. Hopefully, this also resolves the next.js out of memory issue being reported in the Data Capture project.
Regression tested the 6 components in Storybook. No issues found.
Screenshots shows the 6 Circular Dependencies, after these code changes, 0 Circular Dependencies
> fix: 🐛 Fix circular dependencies

- stories/SQFormIconButton.stories.js
- stories/__tests__/SQFormIconButton.stories.test.js
Added some tests for SQFormIconButton. These are generally the same as the tests for SQFormButton since they have similar functions.
✅ Closes: #221
> 💍 Add tests for SQFormIconButton

- stories/SQFormRadioButtonGroup.stories.js
https://www.loom.com/share/08e3b02abded4493a7d887bc511e5813
Ref: #161
> docs: ✏️ add SQFormRadioButtonGroup stories

- src/components/SQForm/SQFormIconButton.js
- stories/__tests__/SQFormIconButton.stories.test.js
> fix: 🐛 pass title to IconComponent svg, update IconButton tests

- stories/SQFormCheckboxGroup.stories.js
https://www.loom.com/share/c2c9fc0cf529407995e0299368e83ca8
Ref: #161
> docs: ✏️ add stories for SQFormCheckboxGroup

- stories/__tests__/SQFormReadOnlyField.stories.test.js
✅ Closes: 254
My first crack at shipping actual tests, so any feedback is appreciated!
> test: 💍 SQFormReadOnlyField

- stories/SQFormResetButtonWithConfirmation.stories.js
https://www.loom.com/share/33399ce7a16748e88888482c5ce7d215
Ref #161
> docs: ✏️ add SQFormResetButtonWithConfirmation story

- stories/SQFormDialogStepper.stories.js
Also simplified the layouts to make testing a bit easier
https://www.loom.com/share/fdd8d050c7e24eac8586eaa4abd497f8
Ref #161
> docs: ✏️ refactor SQFormDialogStepper to use new storybook setup

- stories/SQFormResetInitialValuesButton.stories.js
https://www.loom.com/share/bb46c0fab8b441a9ae5d1152a7968760
Ref #161
> docs: ✏️ add SQFormResetInitialValuesButton story

- src/components/SQForm/SQFormMaskedTextField.js
- stories/SQFormMaskedTextField.stories.js
https://www.loom.com/share/110c7d668aa84472960ebceed52c6624
Ref: #161
> docs: ✏️ add SQFormMaskedTextField story

- stories/SQFormInclusionList.stories.js
https://www.loom.com/share/a4df061da0974f4cb6f6b99fc9731302
Ref #161
> docs: ✏️ add SQFormInclusionList stories

- stories/__tests__/SQFormCheckboxGroup.stories.test.js
Adding in tests for SQFormCheckboxGroup
✅ Closes: #264
> test: 💍 Add SQFormCheckboxGroup Tests

- src/components/SQForm/SQFormIconButton.js
- stories/__tests__/SQFormIconButton.stories.test.js
feat: 🎸 added a prop for sqformIconButton for teal icon
added a prop for sqformIconButton for teal icon
✅ Closes: 288
https://www.loom.com/share/17baf5febaaf4a6689ea0dc871b6f854
> feat: 🎸 added a prop for sqformIconButton for teal icon

- stories/__tests__/SQFormIconButton.stories.test.js
feat: 🎸 fix test for icon button
fix test for icon button
✅ Closes: 297
> feat: 🎸 fix test for icon button

- stories/SQFormMultiSelect.stories.js
- stories/__tests__/SQFormMultiSelect.stories.test.js
> test: 💍 SQFormMultiSelect

- src/utils/consoleWarnings.js
- stories/__tests__/SQFormRadioButtonGroup.stories.test.js
Added tests for the SQFormRadioButtonGroup component
✅ Closes: #271
> test: 💍 SQFormRadioButtonGroup tests

- src/components/SQForm/SQFormMultiValue.js
- stories/SQFormMultiValue.stories.js
SQFormMultiValue now accepts custom initial values as well as avoids
adding custom options to list of options displayed in the autocomplete
dropdown
✅ Closes: #308
Loomeroni: https://www.loom.com/share/9a73405ca68f4d00831abedf2e5e5173
> fix: 🐛 SQFormMultiValue accepts custom initial values

- src/components/SQForm/SQFormDropdown.js
- src/components/SQForm/useForm.js
- stories/SQFormDropdown.stories.js
Adds support for boolean valued dropdowns; modifies _getHasValues on
useForm to account for boolean values
✅ Closes: #174
Please watch the [Loom](https://www.loom.com/share/5a258dd945c343158fdabaee439d1d9c) as it brings up a potential for some more changes.
> feat: 🎸 support for boolean valued dropdown

- src/components/SQForm/SQFormReadOnlyField.js
- src/components/SQForm/SQFormTextField.js
- src/components/SQForm/SQFormTextarea.js
Updated id values to name instead of label for more uniqueness. 
✅ Closes: #318
> fix: 🐛 Updated id values to name instead of label for more uniq

- src/components/SQForm/SQFormIconButton.js
- stories/SQFormDropdown.stories.js
- stories/__tests__/SQForm.stories.test.js
- stories/__tests__/SQFormDropdown.stories.test.js
- stories/__tests__/SQFormIconButton.stories.test.js
Fixed issue with SQFormDropdown where the story name was changed. Also fixed issue where a component was added to SQForm stories.
> Issue 320/fix broken tests

- .github/workflows/CI.yml
- package.json
I believe this is all that's needed to add running tests to the current CI action (🤞)
✅ Closes: #167
> ci: 🎡 add running tests to CI

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
✅ Closes: #279
Removing unused props from the stepper component.
> fix: 🐛 Removed unused props from the stepper component

- src/components/SQForm/SQFormCheckbox.tsx
✅ Closes: #314
Loom of it functioning in storybook https://www.loom.com/share/6bcbc4de7364403eb49ec08f6d3d084a
> refactor: 💡 Convert SQFormCheckbox to typescript Ref #244

- src/components/SQForm/SQFormCheckboxGroup.tsx
✅ Closes: #315
Loom of it functioning in storybook: https://www.loom.com/share/6bcbc4de7364403eb49ec08f6d3d084a
> refactor: 💡 Convert SQFormCheckboxGroup to typescript Ref #244

- src/components/SQForm/SQFormIconButton.tsx
Loom of it functioning in storybook:
https://www.loom.com/share/f2dbc1ccb83e4b41975c4aaf3e82aa5e
> refactor: 💡 Convert SQFormIconButton to typescript Ref #244

- src/components/SQForm/SQFormRadioButtonGroupItem.tsx
#342 
#244 
https://www.loom.com/share/8605c71b1a9746be99ad2a448b7d9d0a
> refactor: Convert SQFormRadioButtonGroupItem to Typescript

- src/components/SQForm/SQFormInclusionListItem.js
- src/components/SQForm/SQFormInclusionListItem.tsx
https://www.loom.com/share/005264408afe47ef9da042fcce148a1f
> refactor: Convert SQFormInclusionListItem to TS Ref #244

- src/components/SQForm/SQFormTextarea.tsx
ScreenCast of this is working in the storybook.
https://www.screencast.com/t/WwXQJTPY37Zd
> refactor: 💡 Converted SQFormTextarea to TypeScript

- src/components/SQForm/SQFormButton.tsx
- src/components/SQForm/SQFormIconButton.tsx
- src/components/SQForm/useFormButton.tsx
#244 
#349 
https://www.loom.com/share/610c2bcfeb1047da97435fd85f8b4e8f
> refactor:  useFormButton to TS

- src/components/SQForm/SQFormTextField.tsx
> refactor: 💡 Convert SQFormTextField to Typescript

- src/components/SQForm/useFormButton.tsx
> refactor: 💡 improve `useFormButton` return types

- package-lock.json
- package.json
- src/components/SQFormScrollableCard/SQFormScrollableCard.js
> Utilize useAutoHeight inside SQFormScrollableCard from SQHook

- src/components/SQForm/SQFormMultiSelect.js
✅ Closes: #313
Loom https://www.loom.com/share/39bfca62199c45aeb4e5f708ff751fe4
> feat: 🎸 Added showTooltip and tooltipText props to SQFormMultiSelect

- package-lock.json
- package.json
- stories/__tests__/SQForm.stories.test.js
- stories/__tests__/SQFormAsyncAutocomplete.stories.test.js
- stories/__tests__/SQFormAutocomplete.stories.test.js
- stories/__tests__/SQFormCheckboxGroup.stories.test.js
- stories/__tests__/SQFormDialog.stories.test.js
- stories/__tests__/SQFormDropdown.stories.test.js
- stories/__tests__/SQFormMultiSelect.stories.test.js
- stories/__tests__/SQFormRadioButtonGroup.stories.test.js
- stories/__tests__/SQFormTextField.stories.test.js
- stories/__tests__/SQFormTextarea.stories.test.js
Upgraded Yup to the latest version at this time of writing and fixed the
broken tests that resulted
BREAKING CHANGE: 🧨 Yup.array().isRequired() is now passed with an empty array.
https://github.com/jquense/yup/blob/master/CHANGELOG.md#breaking-changes-1
✅ Closes: #398
> chore: 🤖 Upgrade Yup to v0.32.x

- src/components/SQForm/SQFormRadioButtonGroup.tsx
- src/components/SQForm/SQFormRadioButtonGroupItem.tsx
✅ Closes: #400
The title says it all.
https://www.loom.com/share/67616ff2a8b34216b5808bf6a1c155e8
> refactor: 💡 Convert SQFormRadioButtonGroup to Typescript

- package-lock.json
- package.json
- src/components/SQForm/useFormButton.js
- src/utils/index.js
Removed some logic that was duplicate and was able to remove a dependency that was no longer needed as a result.
> Remove hasUpdate Util and fast-deep-equal dependency

- src/components/SQForm/SQFormResetButtonWithConfirmation.tsx
✅ Closes: #364
https://loom.com/share/e19ecfefef324c0290565e1a77eb3241
Converting SQFormResetButtonWithConfirmation from JS to TS
> refactor: 💡 convert SQFormResetButtonWithConfirmation to TS

- src/components/SQForm/SQFormAsyncAutocomplete.tsx
- src/components/SQForm/SQFormAutocomplete.tsx
> refactor: 💡 Migrate SQFormAsyncAutocomplete to TS

- stories/components/FormValidationMessage.tsx
- stories/components/FriendsFieldArray.tsx
- stories/components/SQFormStoryWrapper.tsx
> refactor: 💡 Migrate stories/components/* to TS

- src/components/SQForm/SQFormAutocomplete.js
> refactor: 💡 add required prop to make TS happy

- src/components/SQForm/SQFormIconButton.tsx
- src/components/SQForm/useFormButton.tsx
- stories/SQFormIconButton.stories.tsx
- stories/__tests__/SQFormIconButton.stories.test.tsx
Migrate SQFormButtonIconButton.stories and tests to TS
✅ Closes: #422
> refactor: 💡 Migrate SQFormIconButton.stories to TS

- src/hooks/useInitialRequiredErrors.tsx
Loom of it functioning in story book:
https://www.loom.com/share/0549491e5af14c54b0b3993c63225530
> refactor: 💡 Convert useInitialRequiredErrors to typescript Ref #244

- stories/utils/createDocsPage.tsx
> refactor: 💡 Migrate stories/utils/* to TS

- jest.config.js
- stories/SQFormTextField.stories.tsx
- stories/__tests__/SQFormTextField.stories.test.tsx
- stories/components/SQFormStoryWrapper.tsx
- stories/utils/getSizeProp.ts
Migrate SQFormTextField.stories.js and SQFormTextField.stories.test.js
to TS
✅ Closes: #424
> refactor: 💡 Migrate SQFormTextField stories to TS

- .github/workflows/Documentation.yml
Only way I know of to test if this works is to merge the PR 😅 
✅ Closes: #134
> ci: 🎡 Use an Admin token to publish Docs to Protected Branch

- src/components/SQForm/SQFormMaskedReadOnlyField.js
✅ Closes: #452
Loom: https://www.loom.com/share/53bfc709c80a451c940167aafcebf621
> fix: 🐛 Renders - - when no data is provided to MaskedReadOnly

- src/components/SQFormScrollableCard/SQFormScrollableCard.js
- stories/SQFormScrollableCard.stories.js
Expose prop cardContentStyles to allow custom styles to spread onto the
cardContent className
✅ Closes: 466
[Loom demo](https://www.loom.com/share/7612284f3214457581de11ea425959d1)
> feat: 🎸 cardContentStyles prop for SQFormScrollableCard

- src/components/SQFormScrollableCard/SQFormScrollableCard.js
- stories/SQFormScrollableCard.stories.js
✅ Closes: 470
Check out the loom for more details: https://www.loom.com/share/b864a6689f1a4d15b06e59b682e4c163
There are a couple of things my team would like to be able to configure on scrollable card. The changes are passive and default to what they were previously hard coded to.
> feat: 🎸 Configure title variant and square corners

- jest.config.js
- src/components/SQForm/SQFormAsyncAutocomplete.tsx
- src/components/SQForm/SQFormMultiValue.tsx
- src/components/SQForm/SQFormReadOnlyField.tsx
- stories/__tests__/SQFormDatePicker.stories.test.js
> refactor: 💡 Migrate SQFormMultiValue to TS

- package-lock.json
- package.json
Updating the version of scplus-shared-components to get latest fixes
✅ Closes: #495
> chore: 🤖 Update scplus-shared-components version

- src/components/SQForm/SQFormDatePickerWithCalendarInputOnly.js
Datepicker components change handlers were causing runtime errors. Fix
them here.
✅ Closes: #511
Loom: https://www.loom.com/share/fbcfdc640fb6401485c35b2ac0fa36bb
> fix: 🐛 Fix datepicker component change handlers

- src/components/SQForm/SQFormInclusionList.tsx
- src/components/SQForm/SQFormReadOnlyField.tsx
- stories/SQForm.stories.tsx
Migrate SQForm Stories to TS
Loom video details the reasoning behind some of my changes.  Please watch.  
https://www.loom.com/share/28f28f77f2cd4069b796c887c0a5a65e
✅ Closes: #530
> refactor: 💡 Migrate SQForm Stories to TypeScript

- src/components/SQForm/SQFormAsyncAutocomplete.tsx
- stories/SQFormAsyncAutocomplete.stories.tsx
- stories/__tests__/SQFormAsyncAutocomplete.stories.test.tsx
Migrate SQFormAsyncAuotcomplete stories to TS
https://www.loom.com/share/2dc5402be39c4ee2bdb4bc15c4ab9f0c
✅ Closes: #532
> refactor: 💡 Migrate AsyncAutocomplete stories to TS

- src/components/SQForm/SQFormDatePicker.tsx
- stories/SQFormDatePicker.stories.tsx
- stories/__tests__/SQFormDatePicker.stories.test.tsx
Migrate SQFormDatePicker stories and tests to TypeScript.
https://www.loom.com/share/2d87b28eee0240d9b793bad5fef2a320
✅ Closes: #551 and #552
> refactor: 💡 Migrate DatePicker stories to TS

- src/components/SQForm/SQFormHelperText.tsx
Migrate SQFormHelperText to TS.
https://www.loom.com/share/63d9eacd87134af285ee9844a3c1f773
✅ Closes: #555
> refactor: 💡 Migrate SQFormHelperText to TypeScript

- stories/__tests__/SQFormInclusionList.stories.test.js
Adding a test suite for the SQFormInclusionList component.
✅ Closes: #562
> test: 💍 Add tests for SQFormInclusionList

- src/components/SQForm/SQFormMaskedTextField.tsx
- stories/SQFormMaskedTextField.stories.tsx
> refactor: 💡 Migrate SQFormMaskedTextField.stories.js to TS

- stories/SQFormDisableableComponents.stories.tsx
> refactor: 💡 Migrate SQFormDisableableComponents story to TS

- src/components/SQForm/SQFormMultiSelect.tsx
- stories/SQFormMultiSelect.stories.tsx
- stories/__tests__/SQFormMultiSelect.stories.test.tsx
> refactor: 💡 Migrate SQFormMultiSelect.stories.js to TS

- src/components/SQForm/SQFormRadioButtonGroup.tsx
- stories/SQFormRadioButtonGroup.stories.tsx
- stories/__tests__/SQFormRadioButtonGroup.stories.test.tsx
Also convereted the test file
✅ Closes: #576
> refactor: 💡 Migrate SQFormRadiobuttonGroup.stories.js to TS

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
modified selectValues logic for required fields only      ✅ Closes: #554
> fix: 🐛 modified selectValues logic for required fields only

- src/components/SQForm/SQFormMaskedReadOnlyField.tsx
- src/components/SQForm/SQFormResetButtonWithConfirmation.tsx
- src/components/SQForm/SQFormResetInitialValuesButton.tsx
- stories/SQFormMaskedReadOnlyField.stories.tsx
- stories/SQFormResetButtonWithConfirmation.stories.tsx
- stories/SQFormResetInitialValuesButton.stories.tsx
- stories/types/storyHelperTypes.ts
SQFormResetButtonWithConfirmation.stories
SQFormRestInitialValuesButton.stories
SQFormMaskedReadOnlyField.stories
> Issues: 558 559 560 Stories to Typescript 

- src/components/SQForm/SQFormDateTimePicker.tsx
- stories/SQFormDateTimePicker.stories.tsx
> refactor: 💡 Convert SQFormDateTimePicker stories to typescript

- src/components/SQForm/SQFormDatePickerWithCalendarInputOnly.tsx
- stories/SQFormDatePickerWithCalendarInputOnly.stories.tsx
> refactor: 💡 SQFormDatePickerWithCalendarInputOnly stories to TS

- src/components/SQForm/SQFormDatePicker.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
Added optional chaining operator with values[step].length and a
condition that will prevent from assigning null to date
✅ Closes: #584
> fix: 🐛 Added ? operator and modified date clearance logic

- .storybook/styles/root.css
- package-lock.json
- package.json
- src/components/SQFormDialog/SQFormDialogInner.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
Updated the padding and colors of the RoundButton to meet UX designs.  
✅ Closes: #601
> SSC-141 SSC-144 SSC-149 dialog spacing paddings

- stories/__tests__/SQForm.stories.test.tsx
> refactor: 💡 Migrate SQForm.stories.test.tsx to TS

- src/components/SQForm/SQFormMultiValue.tsx
- stories/SQFormMultiValue.stories.tsx
- stories/__tests__/SQFormMultiValue.stories.test.tsx
Migrate SFormMultiValue.stories.js and SQFormMultiValue.stories.test.js
to TS
✅ Closes: #593 & #594
> refactor: 💡 SQFormMultiValue stories and tests to TS

- package-lock.json
- package.json
- rollup.config.js
> fix: 🐛 Revert es module support

- src/components/SQForm/SQFormInclusionList.tsx
- stories/SQFormInclusionList.stories.tsx
> refactor: 💡 SQFormInclusionList stories to TS

- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
- stories/SQFormScrollableCard.stories.tsx
> refactor: 💡 Migrate SQFormScrollableCard stories to TS

- stories/LoadingSpinner.stories.tsx
Migrate LoadingSpinner stories to TypeScript
https://www.loom.com/share/e858a5d8768c4111a37af63f3048c552
✅ Closes: #612
> refactor: 💡 Migrate LoadingSpinner stories to TS

- tsconfig.json
> chore: 🤖 Exclude .ts and .tsx test files from TS Compiling

- stories/__tests__/SQFormInclusionList.stories.test.tsx
> refactor: 💡 Migrate SQFormInclusionlist tests to TS

- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
- stories/SQFormScrollableCardsMenuWrapper.stories.tsx
> refactor: 💡 Migrate SQFormScrollabelCardMenuWrapper story to TS

- stories/SQForm.stories.tsx
- tsconfig.json
✅ Closes: #614
Loom: https://www.loom.com/share/9c1e6209ac344cb9a2560c462f46cd8d
> chore: 🤖 Fix storybook multiselect validation

- SQFormDocs/package-lock.json
- SQFormDocs/src/pages/index.tsx
- SQFormDocs/tsconfig.json
> refactor: 💡 Migrate SQFormDocs/* to TS

- README.md
Updated README for the Typescript conversion to include all breaking
changes that will be introduced. Also updated all references of
"Typescript Version" to be "Version 8"
✅ Closes: #638
> docs: ✏️ Update Typescript README breaking changes

- CHANGELOG.md
- jest.config.js
- package-lock.json
- package.json
- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- stories/SQFormDialog.stories.tsx
- stories/__tests__/SQFormDialog.stories.test.tsx
Configured Jest to ignore `.dts` directory when looking for tests
I've also taken this opportunity to merge `master` into the Typescript branch.
Closes: #640
> chore: 🤖 Jest ignores .dts directory 

- src/components/SQFormDialog/SQFormDialog.js
- src/components/SQFormDialog/SQFormDialogInner.js
- stories/SQFormDialog.stories.js
Add "onTertiaryClick" click handler prop to SQFormDialog component
https://www.loom.com/share/e533c453b8514ac280e4fcd8bc015abd
✅ Closes: #643
> feat: 🎸 Add "onTertiaryClick" click handler to SQFormDialog

- src/components/SQForm/SQFormAutocomplete.tsx
- src/components/SQForm/SQFormCheckboxGroup.tsx
- src/components/SQForm/SQFormDatePicker.tsx
- src/components/SQForm/SQFormDatePickerWithCalendarInputOnly.tsx
- src/components/SQForm/SQFormMaskedTextField.tsx
- src/components/SQForm/SQFormMultiValue.tsx
- src/components/SQForm/SQFormRadioButtonGroup.tsx
- src/components/SQForm/SQFormTextField.tsx
- src/components/SQForm/SQFormTextarea.tsx
- stories/SQFormTextField.stories.tsx
> refactor: 💡 Removes isRequired which has become dead code

- src/components/SQFormDialog/SQFormDialog.tsx
> refactor: 💡 validationSchema optional for all components

- src/components/SQForm/SQFormReadOnly.tsx
> fix: 🐛 Adds enableReinitialize prop to SQFormReadOnly component

- src/components/SQForm/SQFormDatePicker.tsx
Fix hole in `BaseDatePickerProps`.
https://www.loom.com/share/9aa352088e9f4702af3a9db90a8c78b3
✅ Closes: #672
> Issue 672/fix date picker type

- src/components/SQForm/SQFormDatePicker.tsx
- stories/SQFormDatePicker.stories.tsx
✅ Closes: #674
https://www.loom.com/share/7ad06660fc404dc3ac6a1a4f7c3fa559
> fix: 🐛 Fix SQFormDatePicker muiFieldProps type

- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- src/components/SQFormDialog/types.ts
- stories/SQFormDialog.stories.tsx
- stories/__tests__/SQFormDialog.stories.test.tsx
✅ Closes: #677
https://www.loom.com/share/a4450b3223434ea3bfa72f62f0aecb0e
> feat: 🎸 update onTertiaryClick prop to return context

- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- stories/SQFormDialog.stories.tsx
Added a prop to be able to set the SQFormDialog's tertiaryButton variant
✅ Closes: #682
Loom: https://www.loom.com/share/2cf6d71c4005410faf3434102e185b2b
> feat: 🎸 SQFormDialog tertiaryButton variant

- src/components/SQForm/SQFormHelperText.tsx
- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- stories/SQFormDialog.stories.tsx
- stories/__tests__/SQFormDialog.stories.test.tsx
Add HelperText option to SQFormDialog footer
Main Loom: https://www.loom.com/share/6e01befa8fbb40cda9e3f12565134a29
Loom detailing consuming breaking change: https://www.loom.com/share/19a4be8f78634879805ad10ec65d608d
✅ Closes: 695
> feat: 🎸 Add HelperText option to Dialog footer

- src/components/SQForm/SQFormHelperText.tsx
Update SQFormHelperText color to textWarningYellow
https://www.loom.com/share/d2168e6e83144a58b44d2f6e73004603
✅ Closes: #699
> chore: 🤖 Update SQFormHelperText color

- jest.config.js
- src/components/SQForm/SQFormTextField.tsx
- stories/SQFormTextField.stories.tsx
- stories/__tests__/SQFormTextField.stories.test.tsx
I edited the jest config to ignore the `old_stories` directory for tests.
✅ Closes: #708
> refactor: 💡 Migrate SQFormTextField to MUIv5

- src/components/SQForm/SQFormReadOnlyField.tsx
- stories/SQFormReadOnlyField.stories.tsx
- stories/__tests__/SQFormReadOnlyField.stories.test.tsx
Migrate SQFormReadOnlyField to MUIv5
✅ Closes: #713
> refactor: 💡 SQFormReadOnlyField to MUIv5

- src/components/SQForm/SQFormHelperText.tsx
This component does not have any stories on its own to test, but I figured it was small enough to go ahead and make the PR.
✅ Closes: #725
> refactor: 💡 Migrate SQFormHelperText to MUI5

- src/components/SQForm/useForm.tsx
https://www.loom.com/share/740693dde59645158d638834311885f1
✅ Closes: #742
> refactor: 💡 Migrate useForm to MUI5

- src/components/SQForm/SQFormAutocomplete.tsx
- stories/SQFormAutocomplete.stories.tsx
- stories/__tests__/SQFormAutocomplete.stories.test.tsx
Loom: https://www.loom.com/share/bf6799f94a36498797d9de055f4e9958
> Issue 723/migrate autocomplete MUIv5

- SQFormDocs/src/pages/index.tsx
Looks like there was some type errors that were suddenly causing issues with the build-storybook action. This should fix it up.
> chore: 🤖 Fix failing storybook action

- stories/SQFormResetInitialValuesButton.stories.tsx
Migrate ResetInitialvaluesButton to MUI5
https://www.loom.com/share/dd8d25ba1b58435d84d7b93c392168c1
✅ Closes: #756
> refactor: 💡 Migrate ResetInitialButton MUI5

- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- stories/SQFormDialog.stories.tsx
- stories/__tests__/SQFormDialog.stories.test.tsx
> chore: 🤖 Migrate SQFormDialog to MUIv5

- package-lock.json
- package.json
- src/components/SQForm/SQFormDateTimePicker.tsx
- stories/SQFormDateTimePicker.stories.tsx
Please watch the loom as it highlights differences between the previous and latest `DateTimePicker`.
https://www.loom.com/share/77e4f85b79e045eea09389d5635d03b8
✅ Closes: #751
> refactor: 💡 Migrate DateTimePicker to MUI5

- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
- stories/SQFormScrollableCard.stories.tsx
https://www.loom.com/share/44ec39e7e86a4acaa49c76b6236772d8
> Issue 773/Migrate ScrollableCard to MUI5

- src/components/SQFormScrollableCardsMenuWrapper/SQFormScrollableCardsMenuWrapper.tsx
- stories/SQFormScrollableCardsMenuWrapper.stories.tsx
This PR includes the `SQFormScrollableCard` MUI5 migration issue branch.  Please wait on that PR before merging this one.
Update: `SQFormScrollableCard` PR has been merged.
https://www.loom.com/share/13a2b0e1aedc4dbab88f9ef2e358ab76
> Issue 776/Migrate ScrollableCardsMenuWrapper to MUIv5

- .github/CODEOWNERS
Updating the CODEOWNERS file to include Lucas and Laurel which will add
them as Approving Reviewers to future PRs
> chore: 🤖 Update code owners

- package-lock.json
- package.json
- src/components/SQForm/SQFormTextarea.tsx
- stories/SQForm.stories.tsx
> chore: 🤖 Consume SSC@10.1.0

- src/components/SQForm/SQFormTextField.tsx
- src/components/SQForm/SQFormTextarea.tsx
> chore: 🤖 Consolidate Text Field event handlers

- src/components/SQForm/SQFormHelperText.tsx
> chore: 🤖 Fix Spacing On Helper Text

- src/components/SQForm/SQForm.tsx
- src/components/SQFormDialog/SQFormDialog.tsx
- stories/SQForm.stories.tsx
- stories/SQFormDialog.stories.tsx
Reverts SelectQuoteLabs/SQForm#809 due to improper commit formatting.  This is causing a break in the semantic versioning pipeline from releasing a new version.
> Revert "SSR 149 validateOnBlur and validateOnChange options"

- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
- stories/SQFormScrollableCard.stories.tsx
- stories/__tests__/SQFormScrollableCard.stories.test.tsx
provided testing for SQFormScrollableCard submit, reset, style props, header props, validation and helper text.
1. Added testing ID's for container, paper and content as well as story elements such as custom subheader and wrapper
2. Testing from props include
- Submit and Reset props
- Style
- Headers
- Validation
- Helper Text
✅ Closes: #295
Loom: https://www.loom.com/share/1bf8d43f41294ac48a6eb161acc0af3b
> test: 💍 SQFormScrollableCard Tests

- stories/__tests__/SQFormScrollableCard.stories.test.tsx
> chore: 🤖 Remove flaky test

- src/components/fields/SQFormDropdown/SQFormDropdown.tsx
- stories/SQFormDropdown.stories.tsx
Update the current implementation of the Dropdown with added specifications. Here is the current implementation of this SQForm: https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformdropdown--default (this is an example link)
Design reference: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678 
Typography: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946 
Color: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646 
Default:
Label:  Text Style: Label 12 px Weight: 400
Focused:
Label: Text Style: Label 12 px Weight: 400
With Validation:
Label: Text …
> feat: SSR-161 SQFormsDropdown - Update component

- .storybook/preview.tsx
- package-lock.json
- src/components/fields/SQFormAutocomplete/SQFormAutocomplete.tsx
- stories/SQForm.stories.tsx
- stories/SQFormDialog.stories.tsx
Fixed the issue with SQFormAutocomplete field dropdown not scrolling properly
✅ Closes: #862
loom: https://www.loom.com/share/f6d0a5b158934e46a3919289b25ea06f
> fix: 🐛 SQFormAutocomplete scroll

- src/components/SQFormTransferTool/SQFormTransferProductPanels.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/index.ts
- src/components/SQFormTransferTool/types.ts
- src/index.ts
- stories/SQFormTransferTool.stories.tsx
Creates a new component SQFormTransferTool. It is an opinionated, data driven modal to aid in call transfers
loom with some extra explanation: https://www.loom.com/share/58f48fff0e304f789506373aa752fb0b?sid=290e878f-3823-4ff3-976c-bc5a5861d406
> feat: 🎸 SQFormTransferTool

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/SQFormTransferProductPanels.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/types.ts
- stories/SQFormTransferTool.stories.tsx
Expands the previous work, adds processing the content for the accordion body.
loom: https://www.loom.com/share/e1053627eb22426a9ec9e24a60a11a0b?sid=bd853bde-5a23-4077-a813-89506cb8f5bf
> feat: 🎸 Sections in side of the accordions

- src/components/fields/SQFormMultiValue/SQFormMultiValue.tsx
- src/hooks/useForm.tsx
**Jira Description:**
Update the current implementation of the MultiValue with added specifications. Here is the current implementation of this SQForm: https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformmultivalue--default (this is an example link)
Design reference: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678
Typography: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946
Color: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646
Default:
Label: Text Style: Label 12 px Weight: 400
Focused:
Label: Text Style: Label 12 px Weight: 400
With …
> style: 💄 SQForms: MultiValue - Update component

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/DialogInner.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/Step.tsx
- src/components/SQFormTransferTool/types.ts
- stories/SQFormTransferTool.stories.tsx
Loom: https://www.loom.com/share/02a6f6151cae4cc09424981234fc96de
this part one covers much of the step rendering including working with conditions for scripts and questions. 
In the second part of the loom I discuss what is remaining on the overall tool. 
NOTE: many of the questions I pose in the Loom around form validation and also what we save when, have been answered and you can disregard them.
> SC3-1810 step rendering - Part 1

- package.json
- src/components/SQFormTransferTool/SQFormTransferProductPanels.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- stories/SQFormTransferTool.stories.tsx
Given that every field is dropdown with provided options, every field is already valid
So I have removed todo's regarding validation as I feel this is the best path. 
I explain my thinking in the [Loom](https://www.loom.com/share/c1a9de55529f43a5b3a6ac77462d5ab4?sid=98c05987-82b0-4c8a-b5ee-eec50f513d81)
I also make a case for the second storybook script launcher I have added in package.json
I have also done a touch of clean up to remove some console errors for duplicate keys.
> feat: 🎸 Deal with validation - SC3-1810 Part 2

- src/components/SQFormTransferTool/DialogInner.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
Cleans up the loading view - approved by UI/UX
https://www.loom.com/share/ed3cad97d49f4692839b2fc005d6159b?sid=8b0715a4-3d1c-4eba-ab2d-c6bd13999d72
> style: 💄 Clean up the loading view styles

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/types.ts
Some changes needed after the component was actually consumed.
> feat: 🎸 Changes the call back data on transfer
