- .github/workflows/Publish.yml
- release.config.js
Also declared the sematic release plugins
> fix: 🐛 semantic release defaults to repo url in package.json

- src/components/SQFormDialog/SQFormDialog.css
- src/components/SQFormDialog/SQFormDialog.js
- src/components/SQFormDialog/SQFormDialogInner.js
We need to reset the form state when we 'cancel' out of the dialog, so I moved most of the dialog into another custom component, enabling access to `resetForm` from `useSQFormContext`, and put that inside a handler. Additionally, I noticed a small issue when consuming this component re: the DialogActions styles. We weren't getting the `space-between` override we set in CSS, so I moved that to a `classes` object to directly change the MuiDialogActions-root class.
[Loom](https://www.loom.com/share/54bc957125b64fdf8bafbea15ac3f7bd)
> fix: 🐛 reset form state during onclose event

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
✅ Closes: #26
Updated the SQFormDialogStepper to look at the forms dirty state.  This is used to disable the Submit/Next button.  
loom: https://www.loom.com/share/4cebe8c685db4642a55cdff11bae045b
> fix: 🐛 Reading the dirty state on load to disable submit/next

- src/components/SQForm/SQFormDropdown.js
When the dropdown doesn't contain a selected value the empty label - -
will render in the field. When an option is selected, the human-readable
label will render in the field instead of the value.
✅ Closes: #31
Loom: https://www.loom.com/share/8cf9891f28074d70a7429418b4e04d15
> fix: 🐛 Displays - - when empty, displays label instead of value

- src/components/SQForm/SQFormAutocomplete.js
✅ Closes: #38
Spreading the touched fields with the autocomplete touched field so that we don't overwrite the existing touched fields.
Loom shows the existing bug and fix.
Loom: https://www.loom.com/share/38621828a71246e9889085446241b58a
> fix: 🐛 Fixed onBlur event for autocomplete and touched fields SQAH-1268

- src/components/SQForm/SQFormAutocomplete.js
- src/components/SQForm/useForm.js
- stories/SQForm.stories.js
✅ Closes: #43
We can now pass a default value to the autocomplete component.  It also sets the touched property to true so the field shows as valid and not still required.
Loom: https://www.loom.com/share/6c16a4ca15364c6f9871b953d0a0a994
> fix: 🐛 Allow default value to be used in autocomplete component SSC-106

- src/components/SQForm/SQFormTextField.js
- stories/SQForm.stories.js
Allow a HTML5 types to be supplied to SQForm text fields
You can now pass a string for prop `type` to give the the input under SQFormTextField a HTML5 input type
✅ Closes: #45
Loom: https://www.loom.com/share/cc3f1322e3e44ea385f1b978f1bcc935
> feat: 🎸 Allow text fields HTML5 types

- src/components/SQForm/SQFormCheckbox.js
- src/components/SQForm/SQFormDatePicker.js
- src/components/SQForm/SQFormDateTimePicker.js
- src/components/SQForm/SQFormDropdown.js
- src/components/SQForm/SQFormMultiSelect.js
- src/components/SQForm/SQFormReadOnlyField.js
- src/components/SQForm/SQFormTextField.js
- src/components/SQForm/SQFormTextarea.js
- stories/SQFormDialog.stories.js
✅ Closes: 54
I omitted buttons and non-mui field types. My immediate use case for this will be autofocus on a text input in modal.
> feat: 🎸 allow passthrough of props to mui field children

- .github/workflows/Publish.yml
The Publish Github Action began failing after making the master branch
protected. This is because GITHUB_TOKEN doesn't have the required
permissions to write to protected branches. Therefor a Personal Action
Token from an admin account must be used instead.
✅ Closes: #56
> chore: 🤖 Fix semantic release to work with protected branches

- src/components/SQForm/SQFormTextField.js
Added a default placeholder to SQFormTextField of '- -' so if there is
no value it'll show the placeholder by default
Loom video: https://www.loom.com/share/1ec0d7511f014acd8ef4c1ffc90eea0b
✅ Closes: 44
> feat: 🎸 SQFormTextField default placeholder '- -'

- src/components/SQForm/SQFormMultiSelect.js
- stories/SQForm.stories.js
✅ Closes: #53
Added ability for consumer to pass onChange method.
Loom: https://www.loom.com/share/60d6eebb6f8a485395a9d0f66d858ac0
> feat: 🎸 Added onChange handler to multiselect component SSC-107

- src/components/SQForm/SQFormAsyncAutocomplete.js
- src/components/SQForm/SQFormAutocomplete.js
- stories/SQForm.stories.js
✅ Closes: #65
Added onInputProp to allow users to update local state when each key is pressed.  The use case for this is our address fields.  If we start typing an address we send an API request with the values to Smarty Streets and dynamically update the options in the dropdown.
LOOM: https://www.loom.com/share/734652bc9cd141349b2497c3df2a7a91
> feat: 🎸 Added onInputChange prop to autocomplete component SSC-111

- src/components/SQForm/SQFormAutocomplete.js
Closes: [#72 ](https://github.com/SelectQuoteLabs/SQForm/issues/72)
We needed to add a handler in `SQFormAutocomplete` which will trigger on every keyPress, which was added but it is missing the event to return the entered value.
So this PR fixes that issue.
[https://www.loom.com/share/97302a634cd845d39674958f4efd82ed](https://www.loom.com/share/97302a634cd845d39674958f4efd82ed)
> Issue-72-SQFormAutocomplete-missing-event-in-onInputChange

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
- stories/SQFormDialogStepper.stories.js
✅ Closes: #75
Updated the next button enabled/disabled logic.  It now only looks at the current steps values to see if any have been set.  Before it was looking at all values from all steps.  
The touched property is still being set on all fields when the onSubmit is fired in the form.
If we have initial values then the next button will be enabled.
Loom https://www.loom.com/share/0def27c6e270412db50018b750deab0a
> fix: 🐛 Next button logic to look at current step values to enabled/disabled SSC-115

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
- stories/SQFormDialogStepper.stories.js
* Step Number and Title needs 5-10 px space between them 
* Updated step title to be blow number
* Made stepper linear so progression only happens on Next click
* Can still move backwards via the step buttons to completed steps
Before
AFTER
loom: https://www.loom.com/share/cc8db538fedd4f50bed6fc2f20e2f7e8
> SSC-117 Updated to be linear, changed label placement, console warnings removed

- src/components/SQForm/useForm.js
- stories/SQForm.stories.js
✅ Closes: #91
Loom: https://www.loom.com/share/c06513c248454d00b6690c75ad045056
Now, the fulfilled icon only appears when a field is not in an error state and a value is present.
Also fixed a bug where the value `0` (or any falsy number) in a numeric input would be treated as a non-value.
> fix: 🐛 Field is fulfilled if theres no error and theres a value

- package-lock.json
- package.json
Updating Formik to fix bug reported here: https://github.com/formium/formik/issues/2652
I believe this will fix Issue #41 
The bug is difficult to reproduce in a static sandbox, I'll follow up with the developers who have been reporting the issue to see if this resolves the issue or not.
Leaving the issue open until I hear back from the developers reporting the issue.
> fix: 🐛 Update Formik to fix validate onmount bug fixed in 2.1.6

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
✅ Closes: #96
As a user of the stepper
I want to be able to disable the next/submit button until an API call or some other function occurs outside of the Formik context
So that I can stop users from going forward to the next step or submitting.
Loom uses local state that I added to the story.  Couldn't commit it but it was needed for the demo.
https://www.loom.com/share/8049ff6117704737b0080c52af89c0d4
> feat: 🎸 Added ability to disable next in the stepper

- src/components/SQForm/SQFormDropdown.js
✅ Closes: #92 
`SQFormDropdown` now properly shows the orange label and underline when in an error state.
Loom: https://www.loom.com/share/24321e12b6a347caaa1e6b9c73104b99
> fix: 🐛 SQFormDropdown - add error props to InputLabel and Select

- src/components/SQForm/SQFormTextField.js
- stories/SQForm.stories.js
Defines the maximum number of characters the user can enter into the
field; mapped to `input` element `maxlength` attribute. Helper text is
rendered in the component label.
Loom: https://www.loom.com/share/86d7adb6d322416cbbc0aecf51207de6
✅ Closes: #19
> feat: 🎸 add maxCharacters prop to SQFormTextField, rendered in label

- src/components/SQForm/SQFormTextField.js
The initial `useState` value of `valueLength` didn't account for a field's value being `undefined`. More details in the loom about why this was only happening in the "Form with Field Array" story.
https://www.loom.com/share/2df76c585e93494fa83ba0d480779d7c
✅ Closes: #105
> fix: 🐛 add optional chaining to initial value of character counter

- src/components/SQForm/SQFormTextarea.js
- stories/SQForm.stories.js
✅ Closes: #104
Same as #103 but on the textarea component. For better readability I made the value of `characterCounter` a string instead of wrapping it in `<small>` because the label on the "outlined" variant is already pretty small.
> feat: 🎸 add maxCharacters prop to SQFormTextarea

- src/components/SQForm/SQForm.js
- src/components/SQFormDialog/SQFormDialogInner.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
Use nullish coalescing operator (??) instead of or (||) operator to
check for existence of `spacing` value which can be 0 which is falsy
causing unexpected values.
✅ Closes: 114
> fix: 🐛 ?? operator instead of || for grid spacing prop check

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
Adds a max width to the `Stepper` component in `SQFormDialogStepper` based on the amount of steps. This will prevent the steps from being spread really far apart when a wide dialog is used. 
https://www.loom.com/share/8cc3587e951b4188914ccdb3adb58d8f
The base width that's multiplied by the amount of steps is `300` purely because it looked good to me, obviously that can be changed. If necessary, this could easily be made more customizable with some props. 
Some potential ideas:
- `stepMaxWidth={400}`: to make the value completely customizable
- `stepMaxWidth="md"`: to mimic MUI - would need to come up with values for sm/md; false to turn off maxWidth
- `constrainStepWidth={false}`: defaults to true, turns off maxWidth if false
If any I would say `constrainStepWidth` would be the best …
> feat: 🎸 add max width to Stepper steps

- src/components/SQFormDialog/SQFormDialogInner.js
Used `position: sticky` to make the title and actions sections stay in
place while the body scrolls. Demo, deets, and edge case considerations in the loom
https://www.loom.com/share/ec3caa896f654b218bd6a40826bf5427
✅ Closes: #17
> fix: 🐛  make only dialog body scroll

- src/components/SQForm/SQFormAutocomplete.js
setFieldValue was only updating the initialValue of SQFormAutocomplete
so the visible TextField would not reflect the change. Now that we also set the inputValue, the set option will display.
Loom showing fixed example: https://www.loom.com/share/59e0d88fe6aa470cb01ddf8f9261a5e1
✅ Closes: #144
> fix: 🐛 setFieldValue now updates inputValue on SQFormAutocomple

- src/components/SQFormDialog/SQFormDialogInner.js
The default overflowY property of `DialogContent` was conflicting with the child Grid
component's negative margins from its spacing styles
Loom: https://www.loom.com/share/6cb4d2311ec547bca344b60312defb26
(Hopefully you can make out what I'm saying well enough, I forgot there was white noise playing in the background)
✅ Closes: #139
> fix: 🐛 DialogContent overflow causing double scrollbars

- src/components/SQForm/SQFormDatePicker.js
- stories/SQFormDatePicker.stories.js
Date validation was only running on blur of the text element, meaning if
you only used the window, it didn't validate until you focused and
blured the text input or tried to submit. Used setTouched to remedy
this.
✅ Closes: #127
before: https://www.loom.com/share/b8946d66630342f396d11444bac681d9
after: https://www.loom.com/share/e4c1ecd7f8994d25ba53ba5e1518ae8b
There are still some issues here with both the datetimepicker and calendaronlydatepicker components. This did not fix them, I think their issues might be more related to some yup and moment clash but didn't have time to ferret those out in this ticket. I'll try to make an issue demoing both of those issues tomorrow.
> fix: 🐛 run date validation on date picker window close

- src/components/SQForm/SQFormAutocomplete.js
SQFormAutocomplete used to be uncontrolled if you supplied an empty
string iitialValue. This is not something we would expect. These changes
fix that.
✅ Closes: #132
Loom: https://www.loom.com/share/2ac13968b25241cda1542f7cd29ca79b
> fix: 🐛 Autocomplete no longer uncontrolled with '' initialValue

- src/components/SQForm/SQFormDatePicker.js
- src/components/SQForm/useForm.js
Validation errors aren't showing on mount because `isFieldError` uses
`isTouched`. The field won't be considered touched until the user clicks
it, which is why we're seeing the current behavior. If we use `hasValue`
it will show those errors when the field has an initial value.
https://www.loom.com/share/2049ee6738ee477dabb9df1bce9d5596
Also fixes #89: https://www.loom.com/share/1b49b2a0125d4fd8b082097b31c950c0
✅ Closes: #165, #89, #147
> fix: 🐛 correct error state when initial values provided

- src/components/SQForm/SQFormCheckboxGroup.js
- src/components/SQForm/SQFormDropdown.js
- src/components/SQForm/SQFormMultiSelect.js
- src/components/SQForm/SQFormRadioButtonGroup.js
Inputs, labels, and helper text will get error, disabled, and required
state from `FormControl`. Reduces duplication, functionality remains the
same
https://www.loom.com/share/bf0424fdf5e5423fa65d9234f73c3b1d
✅ Closes: #160
> fix: 🐛 change components to use `FormControl` for state props

- src/components/SQForm/SQFormAsyncAutocomplete.js
- src/components/SQForm/SQFormAutocomplete.js
- stories/SQForm.stories.js
SQFormAutocomplete and SQFormAsyncAutocomplete options are now
disableable in the same way that SQFormDropdown options are
✅ Closes: #172
Loom: https://www.loom.com/share/d2856fc315604254ba4573c6d16412d9
> feat: 🎸 SQFormAutocomplete options are now disableable

- package.json
- release.config.js
✅ Closes: #183
This should disable the Semantic-Release bot comments that occur on a PR when a deployment occurs. It's neat to have that comment for historical purposes. However, it's very noisy in our frontend-libraries channel and we can obtain the same information in our Changelog. 
Since I can't really prove CI work in a loom video, here's a link to the documentation for this change. https://github.com/semantic-release/github#options
> ci: 🎡 Disables semantic-release Release comments on PR/issues

- src/components/SQForm/SQFormAutocomplete.js
Added a displayempty prop to SQFormAutocomplete that keeps the empty
option from displaying when not wanted. Able to preserve the
functionality that kept controlled/uncontrolled warnings at bay.
Loom as some good context and explanations. I recommend you watch it.
✅ Closes: #179
Loom: https://www.loom.com/share/2fb9c357b81846b2b46dacde0f2c7bfd
> fix: 🐛 SQFormautocomplete autocomplete displayEmpty prop

- stories/SQFormReadOnlyField.stories.js
- stories/SQFormTextField.stories.js
- stories/SQFormTextarea.stories.js
- stories/components/SQFormStoryWrapper.js
Stories with auto-generated controls and docs. 
You may have noticed that I've been disabling the `name` prop in the controls tab - this is to prevent errors that would be caused by deleting the content of that field (because it's a required prop and we don't have a fallback for when it's empty). Also, if you change the name then submit, the submitted value shows the initial name _and_ the new name, which doesn't represent how the component actually works.
This only affects the prop rendering in Controls, it still shows in the props table in the Docs tab.
https://www.loom.com/share/bc1b17ed9f3e4dfd8175623a96a3e101
✅ Closes: #194
> docs: ✏️ stories for TextField, Textarea, and ReadOnlyField

- stories/components/SQFormStoryWrapper.js
The storybook deploy action has been failing because of the use of
`@material-ui/core/SnackBar`. Hoping that switching to the `Snackbar`
from `scplus-shared-components` will fix this.
Functionality of the snackbar from the `SQFormStoryWrapper` is the same, but it now appears in the top right corner by default
> chore: 🤖 fix `SnackBar` storybook deploy issue

- babel.config.json
- jest.config.js
The tests using stories were failing because
`@storybook/addon-docs/blocks` is using esm, which jest currently does
not understand. I've added that package to the `transformIgnorePatterns`
list in the jest config to solve that, but also had to change the
`.babelrc` to `babel.config.json` due to updates in Babel v7
Apparently, the deal with Babel 7 is that it no longer automatically loads the `.babelrc`. It now has the concept of a `root` directory, which is the current working directory by default, where it looks for a `babel.config.json` file. With this change Jest will be able to properly load the babel config.
References: 
- [similar situation with a different storybook package using esm](https://github.com/storybookjs/storybook/issues/9470#issuecomment-574790318)
- [Babel 7 config …
> chore: 🤖 ignore `@storybook/addon-docs` in jest config

- package-lock.json
- package.json
- stories/SQFormDropdown.stories.js
Refactored the dropdown story to handle passing props to the SQForm
wrapper when testing. Also, the `@storybook/testing-react` package will
be needed to properly compose the args on the component when testing.
In this loom I copied these changes over to @laurelbean's PR #180 to demo how it works
https://www.loom.com/share/5540a09c66e440e0be7aa5bca62aa2df
> docs: ✏️ add story testing package, refactor dropdown story

- src/components/SQForm/SQFormAsyncAutocomplete.js
- src/components/SQForm/SQFormAutocomplete.js
When the autocomplete was disabled it also hid the dropdown arrow - this
was caused by `freeSolo={isDisabled}` (added in #136) on the Mui Autocomplete. I
switched that to `disabled={isDisabled`, so now when the component is
disabled the arrow is still visible, but not clickable. This more
closely resembles the disabled behavior of SQFormDropdown.
Also added the same prop to `SQFormAsyncAutocomplete`
https://www.loom.com/share/38c7e8f8a5384021ab438ab22921f471
✅ Closes: #213
> fix: 🐛 dropdown arrow visible when autocomplete disabled

- src/components/SQFormDialogStepper/SQFormDialogStepper.js
In SQFormDialogStepper the submit button's disabled state is determined
by the validated fields being truthy or falsy. When some fields had
initial values while others did not, the submit button would be enabled
even if required fields were not filled in. This error is caused by the
truthy check being performed with `.some()`, which means as long as one
field is truthy the submit button would enable. I've replaced that with
`.every()`, so all fields have to pass the test before the button
enables.
https://www.loom.com/share/5d8c4a92d02743498a22a2a2a23da853
✅ Closes: #81
> fix: 🐛 DialogStepper next step validation

- src/components/SQForm/SQFormDropdown.js
- src/components/SQForm/SQFormMultiSelect.js
Fixed the components that misaligned bottom borders due to the MUI Select. SQFormDropdown and SQFormMultiselect.
Before: 
After:
> issue-212: Fix misaligned select field

- stories/SQFormButton.stories.js
- stories/__tests__/SQFormButton.stories.test.js
Adding tests for the SQFormButton stories.
I moved the order of the args in the stories so that I could override the onClick with a mock/spy function.
✅ Closes: #217
> test: 💍 Add SQFormButton tests

- src/components/SQForm/SQFormCheckboxGroup.js
- stories/SQForm.stories.js
SQFormCheckboxGroup's select all checkbox is a normal checkbox and has a
dynamic name allowing for multiple select all checkboxes.
✅ Closes: #234
> fix: 🐛 SQFormCheckboxGroup select all is a normal checkbox

- src/components/SQForm/SQFormCheckboxGroupItem.js
- src/components/SQForm/SQFormRadioButtonGroupItem.js
There's not enough space between radio/checkbox items when the items
have text that wraps, which makes it harder to read. This PR adds a
small margin-bottom to the items
Before:
After:
✅ Closes: #227
> fix: 🐛 add spacing below radio/checkbox items

- src/components/SQForm/SQFormCheckboxGroup.js
- stories/__tests__/SQForm.stories.test.js
The key was missing for SQFormCheckboxGroup's select all checkbox
causing console warnings
✅ Closes: #245
> fix: 🐛 SQFormCheckboxGroup Select all missing key

- src/components/SQForm/SQFormAsyncAutocomplete.js
SQFormAsyncAutocomplete requires a callback fn handleAsyncInputChange so
we need to update its proptype def to required
✅ Closes: 208
> docs: ✏️ make handleAsyncInputChange func prop required

- src/components/SQForm/SQFormDatePicker.js
Users could still open calendar input on a disabled calenderonly date
picker, and even change the date. This fixes that.
✅ Closes: #260
Loooooom https://www.loom.com/share/c0aa2c65e908403ab88d7290a7b92f3d
> fix: 🐛 Ensure users cant open calendar input on disabled picker

- src/components/SQForm/SQFormAutocomplete.js
When resetting an entire form, all autocompletes would reset to empty
string, even if their default state should be '- -'. This fix handles
both cases correctly.
✅ Closes: #250
LoOoOoOOoOO0oom https://www.loom.com/share/6d4a93ccba264c59a52e4fe39bd93565
> fix: 🐛 Correctly reset displayempty autocomplete to '- -'

- .storybook/selectQuoteTheme.js
Fix broken logo image in storybook (top left)
✅ Closes: #262
The below structure change seems to fix it, not sure why ¯\_(ツ)_/¯
I did find some still open issues on storybook's github about theming cache issues, see https://github.com/storybookjs/storybook/issues/13200
Adding the following seemed to clear it out and let me see the fixed logo. I didn't want to commit it since I don't really know what it might impact for a logo fix (low value) but something to try if you can't get theme changes to show in your local version.
> docs: ✏️ Fix broken logo image in storybook (top left)

- stories/__tests__/SQFormDialog.stories.test.js
I wrote some basic tests for SQFormDialog. I didn't want to get too complicated with these because already have tests for SQForm more generally, as well as a lot of our inputs, so I tried to focus on the "dialog" part of things, specifically the `title` prop, the `onSave` and `onClose` callbacks (including the save button enabled/disabled integration with validationSchema), and the auto-focus feature.
As always, any feedback is great, as I'm somewhat new to writing tests.
> Issue 268  -- SQFormDialog.stories.test.js

- stories/SQFormCheckboxGroup.stories.js
Changing the initial value of the checkbox group from a string to an
empty array stops the failed prop error from occurring.
✅ Closes: #273
> chore: 🤖 Update SQFormCheckbox story initial value

- src/components/SQFormDialog/SQFormDialogInner.js
Adding 20px padding to DialogContent used by the SQFormDialog component.
BREAKING CHANGE: 🧨 Changed SQFormDialog content padding to 20px from 8px 24px
✅ Closes: #88
Loom: https://www.loom.com/share/6ead5c0298f24e4f80533f2d3e05d1af
> feat: 🎸 adding 20px padding to DialogContent used by the SQFormDialog component

- package.json
I ran into this same issue last week on the multi divisional admin TypeScript project.
The ESLint TS related rules would throw warnings for most of its linter rules.
Setting the max number of warnings to 0 will cause a non-zero exit code when warnings occur will allow lint-staged to fail the commit and show the warning/errors like we desire.
> chore: 🤖 Treat ESLint TS warnings as errors for pre-commit

- src/components/SQForm/SQFormIconButton.js
- stories/__tests__/SQFormIconButton.stories.test.js
The icon size and color were not rendering properly because of the props not being passed to the icon properly
Screenshots show the component in storybook rendering as expected:
Removed the color test because testing styles should be done with visual regression/e2e tests. There's no reliable way via RTL unit tests to test css variables
✅ Closes: #331
> fix: 🐛 correctly pass props to Icon

- src/components/SQForm/SQFormMaskedTextField.js
If `stripNonNumeric` is true it will, on change, set the field's value
to the current input value with all non-numeric characters removed
https://www.loom.com/share/ecf2e22264384db09e4b9aabcfcd4d38
✅ Closes: #224
> feat: 🎸 add `stripNonNumeric` prop to `SQFormMaskedTextField`

- src/components/SQForm/SQFormAutocomplete.js
- stories/SQForm.stories.js
Here is the ticket for these changes https://selectquote.atlassian.net/browse/SSC-134
The issue was the autocomplete's dropdown of options was limited to the field's size in the form which caused issues with readability of the options. I increased the width of the dropdown to be 2X the width of the field but with a limit so that it doesn't run off the screen. I also added tooltips to all the options.
**Loom**: https://www.loom.com/share/609c71187ca84dc6925ea88a5652e846
Note: The loom shows the tooltip text in middle of the row, I've updated it to be on the bottom-left so it now shows directly below the value for very large dropdowns.
> fix: 🐛 gave autocomplete dropdown tooltips and larger size

- src/components/SQForm/SQFormButton.js
- src/components/SQForm/SQFormIconButton.js
- src/components/SQForm/SQFormResetButtonWithConfirmation.js
- src/components/SQForm/SQFormResetInitialValuesButton.js
- src/components/SQForm/useFormButton.js
✅ Closes: #355
Fixed a bug in SQFormButton/useFormButton where the `isDisabled` prop was not used when the button was of type `reset`. Also updated useFormButton to accept an object instead of a multiple params since some params were not always provided.
> fix: 🐛 bug in SQFormButton to prioritize isDisabled over state

- src/components/SQFormGuidedWorkflow/PropTypes.js
- src/components/SQFormGuidedWorkflow/SQFormGuidedWorkflow.js
- stories/SQFormGuidedWorkflow.stories.js
✅ Closes: #390
This gives the consumer access to the current context of the Guided Workflow when clicking the "Next" button
https://www.loom.com/share/1ce5b19a89d242dd811548166d3a2acb
> fix: 🐛 Provide task modules context to user onSubmit

- src/components/SQFormGuidedWorkflow/SQFormGuidedWorkflow.js
- src/components/SQFormGuidedWorkflow/useGuidedWorkflowContext.js
- src/components/SQFormGuidedWorkflow/useManageTaskModules.js
- stories/SQFormGuidedWorkflow.stories.js
Before if you passed in isDisabled to a task module, it would still open
the module and let you make changes. Now enabling the next module will
skip disabled modules until it finds the next enabled one or it reaches
the end.
Loom showing updates: https://www.loom.com/share/5a3616d36a6c494897043a63510aabd5
> Issue 405/ SQFormGuidedWorkflow skips disabled modules

- src/components/SQFormScrollableCardsMenuWrapper/SQFormScrollableCardsMenuWrapper.js
- src/components/SQFormScrollableCardsMenuWrapper/index.js
- src/index.js
- stories/SQFormScrollableCardsMenuWrapper.stories.js
A wrapper to map CardPopoverMenu items to instances of
SQFormScrollableCard to put many forms "into" one card.
✅ Closes: #347
[Made a loom with further explanation. ](https://www.loom.com/share/c323f1756ce94852acc0471693e04a27)
Tl;Dw -- Admin View project needs a way to use the CardPopoverMenu to flip between multiple instances of SQFormScrollableCard. This new component solves that problem, and my solution ended up largely motivated by making it easier to incorporate into existing code, so let me know what you think!
> feat: 🎸 SQFormScrollableCardsMenuWrapper

- src/components/SQFormScrollableCard/SQFormScrollableCard.js
- stories/SQFormScrollableCardsMenuWrapper.stories.js
✅ Closes: 436
I know this is probably not the ideal solution to the problem, but SQFormScrollableCard is pretty critical to MIAV and we need to address the issue with `isSelfBounding` not working and causing us to write more custom add-on stuff inside the MIAV. We know the code proposed here works, and consuming `useAutoHeight` with other components seems to work as expected, but we've investigated this issue within SQFormScrollableCard and cannot seem to figure it out. Our short term solution is to go back to what worked before. In the future, we can devote more time to figuring out why `useAutoHeight` doesn't work in this particular case, but this PR gets folks a working SQFormScrollableCard.
> fix: 🐛 fix isSelfBounding issue in SQFormScrollableCard

- src/components/SQForm/SQFormMaskedReadOnlyField.js
- src/components/SQForm/SQFormReadOnlyField.js
- src/index.js
- stories/SQFormMaskedReadOnlyField.stories.js
- stories/SQFormReadOnlyField.stories.js
Created a new component SQFormMaskedReadOnlyField
It's a pretty common use case, it seems, to want to display masked data in a read only format. `isDisabled` on SQFormMaskedTextField changes the styling to be "disabled" which is no good and, as described in #444, there are hacky ways to do it but this seems like a good solution.
I created a new component instead of exposing something like `isReadOnly` on the original component to stay in line with how the vanilla `SQFormTextField` and `SQFormReadOnlyField` components are.
Also, checkout this 🔥  🔥  🔥 🔥  🔥 🔥  🔥 🔥  UI
closes #444
> feat: 🎸 New component: SQFormMaskedReadOnlyField

- .eslintignore
✅ Closes: #454
Linter no longer attempts to lint compiled JS files in the `/docs` directory
> chore: 🤖 Linter - Ignore docs directory

- src/components/SQFormDialog/SQFormDialog.js
- src/components/SQFormDialog/SQFormDialogInner.js
- stories/SQFormDialog.stories.js
- stories/__tests__/SQFormDatePicker.stories.test.js
- stories/__tests__/SQFormDialog.stories.test.js
UX has requested we offer a way to hide the secondary button to enforce users to take an action in a dialog.  
Closes: #482 
Loom: https://www.loom.com/share/3469d74003e5468991249b27f832d4ef
> Added ability to hide the secondary button in the SQFormDialog

- src/components/SQFormGuidedWorkflow/PropTypes.js
- src/components/SQFormGuidedWorkflow/SQFormGuidedWorkflow.js
We need to pass a dynamic style to the container of SQFormGuidedWorkflow. currently we have <Section style={{padding: '20px'}}>
Which is fixed to 20px. In senior, we need a dynamic padding in our scenario we need it to 0px.
That's why we need a style prop.
> fix: 🐛 add style prop for container of guided workflow

- .eslintrc.json
- src/components/SQForm/SQFormCheckboxGroup.tsx
- src/components/SQForm/SQFormCheckboxGroupItem.tsx
- src/components/SQForm/SQFormDropdown.tsx
- src/components/SQForm/SQFormMultiSelect.tsx
- src/components/SQForm/SQFormRadioButtonGroup.tsx
- src/components/SQForm/SQFormTextarea.tsx
- src/components/SQForm/useForm.tsx
Added generics to useForm hook. Also converted SQFormMultiSelect to TS
and SQFormDropdown to TS, and updated other components that use the hook
as proof that the generics work
✅ Closes: #337
✅ Closes: #394
✅ Closes: #332 
See #338 for conversation, code, and loom videos that explain the situation _super_ well and was largely the inspiration for the changes in this PR.
> refactor: 💡 Add generics to useForm hook

- src/components/SQForm/SQFormHelperText.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
- stories/SQForm.stories.js
- stories/SQFormDialogStepper.stories.js
The justify prop on Grid components was renamed to justifyContent. After
updating that I noticed that SQFormDialogStepper had 2 new error logs.
So I added defaults for missing required props and added a type to the
children PropTypes.
✅ Closes: #499
> fix: 🐛 Update deprecated justify prop for Grid

- stories/__tests__/SQFormIconButton.stories.test.js
In the tests for SQFormIconButton there was one that was testing the
type 'button'. However, that type is no longer a valid one. So removing
that test stops the warning log.
✅ Closes: #501
> test: 💍 Remove test of removed type SQFormIconButton

- README.md
- src/components/SQForm/SQFormDropdown.tsx
- src/components/SQForm/SQFormMultiSelect.tsx
- src/types/Option.ts
- stories/SQFormDropdown.stories.js
Fixed SQFormDropdown and SQFormMultiSelect components from using boolean
valued options. Now, options are no longer allowed to be boolean valued
BREAKING CHANGE: 🧨 Components options are no longer allowed to have boolean values
✅ Closes: #504
> fix: 🐛 Fixed components using boolean valued options

- src/components/SQForm/SQFormAutocomplete.js
While running tests for SQFormAutocomplete, the same warning is thrown every test. 
`Warning: [JSS] Cannot set property 'parentStyleSheet' of undefined`
This was solved by returning undefined instead of empty string so that the conditional styles would not be included if they were not needed (instead of setting them to empty string)
Loom: https://www.loom.com/share/46fbdd0781e14e07bc7a4130080dba0c
✅ Closes: #510
> fix: 🐛 SQFormAutocomplete fix JSS warning

- src/components/SQForm/SQFormTextarea.js
The props rows and rowsMax for SQFormTextarea are deprecated. Now we
need to use minRows and maxRows. However, in order to avoid a breaking
change, I left the original prop names intact and only updated the prop
names we send to the underlying Mui component.
✅ Closes: #517
> fix: 🐛 Update deprecated props SQFormTextarea

- package-lock.json
- package.json
- stories/SQFormGuidedWorkflow.stories.js
Updating to the latest scplus-shared-component version to get the test
fixes for SQFormGuidedWorkflow tests. Also removed all the console.log
statements in the stories for SQFormGuidedWorkflow to further reduce
logs while testing.
✅ Closes: #520
> fix: 🐛 Update scplus-shared-component version

- src/components/SQFormGuidedWorkflow/AdditionalInformationSection.js
- src/components/SQFormGuidedWorkflow/PropTypes.js
- src/components/SQFormGuidedWorkflow/SQFormGuidedWorkflow.js
- stories/SQFormGuidedWorkflow.stories.js
Added the ability for the SQFormGuidedWorkflow component to have an
additional section above the agent script section.
✅ Closes: #586
Loom: https://www.loom.com/share/89ea19daa1ec4588bbc24ca2db0505c2
> feat: 🎸 SQFormGuidedWorkflow additional section

- stories/__tests__/SQFormDialogStepper.stories.test.tsx
✅ Closes: #588
Actually changing the file to TS. Somehow the first time the file extension went from `js` to `jsx` instead of `tsx`. So fixed it.
> refactor: 💡 Migrate SFormDialogStepper tests to TS

- src/components/SQForm/SQFormAsyncAutocomplete.tsx
- src/components/SQForm/SQFormAutocomplete.tsx
- src/components/SQForm/SQFormButton.tsx
- src/components/SQForm/SQFormCheckboxGroupItem.tsx
- src/components/SQForm/SQFormDropdown.tsx
- src/components/SQForm/SQFormInclusionList.tsx
- src/components/SQForm/SQFormMaskedReadOnlyField.tsx
- src/components/SQForm/SQFormMaskedTextField.tsx
- src/components/SQForm/SQFormMultiSelect.tsx
- src/components/SQForm/SQFormMultiValue.tsx
- src/components/SQForm/SQFormTextField.tsx
- src/components/SQFormGuidedWorkflow/AdditionalInformationSection.tsx
- src/components/SQFormGuidedWorkflow/AgentScript.tsx
- src/components/SQFormGuidedWorkflow/Header.tsx
- src/components/SQFormGuidedWorkflow/OutcomeForm.tsx
- src/components/SQFormGuidedWorkflow/SQFormGuidedWorkflow.tsx
- src/components/SQFormGuidedWorkflow/Types.ts
- src/components/SQFormGuidedWorkflow/useGuidedWorkflowContext.ts
- src/components/SQFormGuidedWorkflow/useManageTaskModules.ts
- src/types/MaskTypes.ts
- src/types/Option.ts
- src/types/index.ts
- stories/SQFormButton.stories.tsx
- stories/SQFormGuidedWorkflow.stories.tsx
- stories/SQFormMaskedReadOnlyField.stories.tsx
- stories/SQFormMaskedTextField.stories.tsx
Renamed some of the types that were poorly named like "Props" or
"HeaderProps" to things that are more descriptive, less likely have to
collisions, and are more easily identifiable.
✅ Closes: #627
> refactor: 💡 Rename poorly named exposed types

- src/components/SQFormDialog/SQFormDialogInner.js
- src/components/SQFormDialogStepper/SQFormDialogStepper.js
✅ Closes: #646
We are using a deprecated prop disableBackdropClick. This resolves the SQForm usage, but it is still being used in scplus-shared-components. I will open a task to resolve that. Please watch the loom. This started with me investigating issues on the Typescript branch. Since the issue is not rooted in the TS work, I have fixed it here and will merge it into the TS branch after this is merged. 
https://www.loom.com/share/afd552c8943d4c069ae5c7f1d80a5dd9
> fix: 🐛 Removing deprecated MUI Dialog prop disable Bg click

- src/components/SQFormGuidedWorkflow/Types.ts
- stories/SQFormGuidedWorkflow.stories.tsx
- stories/__tests__/SQFormGuidedWorkflow.stories.test.tsx
SQFormGuidedWorkflow scriptedText prop now accepts ReactNode instead of
just a string
Screenshot showing the use of this new type in Storybook below
✅ Closes: #658
> refactor: 💡 SQFormGuidedWorkflow scriptedText accepts ReactNode

- src/index.ts
Exporting Formik types so that SQForm consumers can use them. I packed the library and tested it locally and was able to import the type and use it.
✅ Closes: #660
> refactor: 💡 Export Formik types SQForm relies on

- README.md
- package-lock.json
- package.json
✅ Closes: #666
Consuming TS projects are always responsible for managing their types. Updated the readme to include our recommended types packages to install.
Screenshot shows all tests now pass
> fix: 🐛 Tests pass - changed react-text-mask types to a devDep

- src/components/SQFormDialog/SQFormDialog.tsx
tertiaryStatus prop is now optional on SQFormDialog
✅ Closes: #680
> fix: 🐛 tertiarystatus is now optional on SQFormDialog

- src/components/SQForm/SQFormAsyncAutocomplete.tsx
SQFormAsyncAutocomplete onChange prop no longer accepts boolean as a
valid param type
✅ Closes: #685
> fix: 🐛 SQFormAsyncAutocomplete onChange doesn't accept boolean

- src/components/SQForm/SQFormAsyncAutocomplete.tsx
SQFormAsyncAutocomplete props `loading`, `open`, `onOpen`, and `onClose`
are marked as optional noww
✅ Closes: #688
> fix: 🐛 Marked SQFormAsyncAutocomplete props as optional

- src/components/SQForm/SQFormRadioButtonGroup.tsx
- stories/SQFormRadioButtonGroup.stories.tsx
SQFormRadioButtonGroup accepts children in shape of array of React
Elements
✅ Closes: #693
[Loom demo](https://www.loom.com/share/70a3d9175fb2441796db5ac78165f878)
This addresses an issue originating [from AQE2](https://selectquote.atlassian.net/browse/AQE2-1084)
> feat: 🎸 SQFormRadioButtonGroup accepts React Element child arr

- src/components/SQFormDialog/SQFormDialogInner.tsx
Ariel discovered an issue with how the SQFormHelperText was working with the new `isValidState` prop.  This small PR fixes that.
https://www.loom.com/share/e9a7a21eae3142869ae6911d5a6bed8c
> fix: 🐛 Fixed issue with how SQFormHelperText chose type

- stories/SQFormMaskedReadOnlyField.stories.tsx
- stories/SQFormMaskedTextField.stories.tsx
https://www.loom.com/share/8b6237794aaf443082143966493c62da
Migrates `SQFormMaskedTextField` and `SQFormmaskedReadOnlyField`.
✅ Closes: #732
> refactor: 💡 Migrate MaskedTextField to MUI5

- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
- stories/SQFormScrollableCard.stories.tsx
Provides and optional icon prop to supply the scrollable card an icon to
place to the left of the title.
✅ Closes: 744
https://www.loom.com/share/ce72e1c67e404ea4981e113bd4069120
> feat: 🎸 Adds icon prop to scrollable card

- notes/SQFormDatePicker.md
- src/components/SQForm/SQFormDatePicker.tsx
- src/components/SQForm/SQFormDatePickerWithDateFNS.tsx
- stories/SQFormDatePicker.stories.tsx
- stories/SQFormDatePickerWithDateFNS.stories.tsx
- stories/__tests__/SQFormDatePicker.stories.test.tsx
- stories/__tests__/SQFormDatePickerWithDateFNS.stories.test.tsx
`SQFormDatePicker`: https://www.loom.com/share/f5758d90e3104eaeac4a1e1f895e2c2f
`SQFormDatePickerWithDateFNS`: https://www.loom.com/share/147125be9eba44ccb80ea057a08c6853
✅ Closes: #745 #748
> refactor: 💡 Migrate DatePicker to MUI5

- stories/SQFormResetButtonWithConfirmation.stories.tsx
Migrate ResetButtonWithConfirmation to MUI5. There were no component changes needed, just moving the story file and making some minor adjustments.
https://www.loom.com/share/b566937658de4f70b70469c1b1a123fe
✅ Closes: #754
> refactor: 💡 Migrate ResetButton to MUI5

- .github/workflows/Storybook.yml
Storybook deployment was failing. It looks like, based on the erorrs, that it was unable to find node_modules in the SQFormDocs directory. Not sure why this is happening all the sudden. 
Between all our actions I wasn't able to find a place where the SQFormDocs node_modules were being installed. so I added that to the storybook action and hopefully that'll fix it.
I was able to reproduce the same issue locally by removing my local ./SQFormDocs/node_modules and trying to run `npm run build-storybook`. Doing so gave me the same error locally we were seeing on the Pipeline. After reinstalling node_modules it passed. So trying this out 🤷
> chore: 🤖 Fix failing storybook deployment

- .github/workflows/Storybook.yml
Turns out you can't use `cd` in the pipeline but we can use the --prefix flag to install them without needing to be in that directory.
> chore: 🤖 Fix installation of node_modules in SQFormDocs

- src/components/SQFormGuidedWorkflow/OutcomeForm.tsx
- src/components/SQFormGuidedWorkflow/Types.ts
The only place we use the `OutcomeForm `component is the `SQFormGuidedWorkflow` component which has not been migrated yet (issue here: https://github.com/SelectQuoteLabs/SQForm/issues/766).  These changes are quite minimal, but if people have a preference to wait on this PR until that component has been completed, we can certainly do that.
✅ Closes: #770
> refactor: 💡 Migrate OutcomeForm to MUI5

- .storybook/styles/AgGrid.css
- .storybook/styles/fonts.css
- .storybook/styles/index.css
- .storybook/styles/root.css
- src/components/SQForm/useForm.tsx
- src/types/theme.d.ts
- stories/SQFormTextField.stories.tsx
- stories/__tests__/SQFormAsyncAutocomplete.stories.test.tsx
- stories/__tests__/SQFormAutocomplete.stories.test.tsx
- stories/__tests__/SQFormCheckboxGroup.stories.test.tsx
- stories/__tests__/SQFormDatePicker.stories.test.tsx
- stories/__tests__/SQFormDatePickerWithDateFNS.stories.test.tsx
- stories/__tests__/SQFormDropdown.stories.test.tsx
- stories/__tests__/SQFormRadioButtonGroup.stories.test.tsx
- stories/__tests__/SQFormTextField.stories.test.tsx
- stories/__tests__/SQFormTextarea.stories.test.tsx
Update HelperText styles to utilize the new MUIv5 theme from SSC
✅ Closes: #779
For all screenshots - New on left, old on right
> chore: 🤖 Update HelperText styles

- README.md
- src/components/SQFormDialogStepper/SQFormDialogStepper.tsx
- stories/SQFormDialogStepper.stories.tsx
- stories/__tests__/SQFormDialogStepper.stories.test.tsx
SQFormDialogStepper validation now respects validation schema properly.
SQFormDialogStepper now validations on mount.
BREAKING CHANGE: 🧨 SQFormDialogStepper respects validation schema
✅ Closes: #790
Loom: https://www.loom.com/share/6cd90ed9ec124121b0a72a187fbe0dc8
**DO NOT MERGE UNTIL #793 is merged**
> fix: 🐛 SQFormDialogStepper validation works properly

- src/components/SQFormDialog/SQFormDialog.tsx
- src/components/SQFormDialog/SQFormDialogInner.tsx
- stories/__tests__/SQFormDialog.stories.test.tsx
throwAlertOnCancel allows the option to override the Are You Sure dialog when cancelling SQFormDialog while in the middle of filling out. Set to true and will throw alert by default (same as previous behavior).
✅ Closes: #806
loom video!  https://www.loom.com/share/5f77ebacb0c049c2973b1135ce0bd60d
> feat: 🎸 throwAlertOnCancel control prop for SQFormDialog

- src/components/SQForm/SQForm.tsx
- src/components/SQFormDialog/SQFormDialog.tsx
- stories/SQForm.stories.tsx
- stories/SQFormDialog.stories.tsx
This adds the feature to be able to control if we are validating onChange or onBlur for both the SQForm and SQFormDialog components.  By default both are set to true (as they have behaved previously), and each can be deactivated by setting to false.
closes issue [#808 ](https://github.com/SelectQuoteLabs/SQForm/issues/808)
Ticket [SSR-149](https://selectquote.atlassian.net/browse/SSR-149?atlOrigin=eyJpIjoiNTc4MDcwYjk1OTBjNGQ1ZDk2YzdlMWJlNzY4YTc4ZTEiLCJwIjoiaiJ9)
[Loom video demoing new feature and stories](https://www.loom.com/share/2d032be41aee4e0f9f5afebde7bb0224)
> SSR 149 validateOnBlur and validateOnChange options

- src/components/SQForm/SQForm.tsx
- src/components/SQFormDialog/SQFormDialog.tsx
- stories/SQForm.stories.tsx
- stories/SQFormDialog.stories.tsx
This adds the feature to be able to control if we are validating onChange or onBlur for both the SQForm and SQFormDialog components.  By default both are set to true (as they have behaved previously), and each can be deactivated by setting to false.
closes issue [#808 ](https://github.com/SelectQuoteLabs/SQForm/issues/808)
Ticket [SSR-149](https://selectquote.atlassian.net/browse/SSR-149?atlOrigin=eyJpIjoiNTc4MDcwYjk1OTBjNGQ1ZDk2YzdlMWJlNzY4YTc4ZTEiLCJwIjoiaiJ9)
[Loom video demoing new feature and stories](https://www.loom.com/share/2d032be41aee4e0f9f5afebde7bb0224)
> SSR 149/Validate onBlur Option

- src/components/SQForm/SQFormHelperText.tsx
- src/components/SQFormScrollableCard/SQFormScrollableCard.tsx
Description
As a developer, I need to update the SQForm components, so that they match design library patterns.
Updates needed on SQFormScrollableCard:
Follow specifications per component design: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A13147) 
Changes needed:
- Header = 49px height
1. (Text style H5 of 24pt weight 400 + 12px padding above below header + 1px divider line)
- Footer =,47px height
1. (Button height = 30px + 8px padding above below header + 1px divider line)
2. Padding around content should be 24px top, 16px left and right, and 32px bottom
- SQFormHelperText component
1. Update helperText to text style Subtitle2 (14pt, weight 600). Reference: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC …
> Ssr 169/update scrollable card styles

- src/components/SQFormDialog/SQFormDialogInner.tsx
Description
Link for Inspect: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A13147) 
Update the SQformDialog component with the following specs:
SQFormDialog 
Header: 
Text: H5 (24pt; Regular/400)
Padding above/below text: 12px
Padding left/right text: 16px
Divider: 1px, B3B3B3
Total header height = 48px
Body:
Set padding around container to 16px top, left, right; 32px bottom
Footer
Divider: 1px, B3B3B3
Padding above/below buttons: 8px
Padding left/right buttons: 16px
Button color: Should be updated to [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A10320) 
Total footer height = 47
Adjusted padding, divider color and header varient of the mentioned SQFormDialog sections
✅ …
> Dialog, DialogAlert, and DialogForm shared component updates

- stories/__tests__/SQFormScrollableCard.stories.test.tsx
Attempting to fix failing CI pipeline tests by moving scope of SQFormScrollableCard submit mock to inside the scope of the test it is working with.
✅ Closes: #826
[1_ci (1).txt](https://github.com/SelectQuoteLabs/SQForm/files/10439215/1_ci.1.txt)
> fix: 🐛 SQFormScrollableCard submit mock fix

- src/components/SQForm/useForm.tsx
- updated HelperTextComponent success badge size to 9x11 px
Loom: [link here](https://www.loom.com/share/00623982858d4c2f9b6d9b0daa1de05d)
NOTE: This is an update to useForm and effects anywhere that HelperTextComponent is used.  Not just SQFormTextField.
✅ Closes: #830
> style: 💄 Update HelperTextComponent success badge size

- .storybook/styles/index.css
Changelog and Intro documentation stories were importing markdown documentation, but once the markdown was rendered, there was no way to scroll it.  This adds overflow visible back in so the rest of the docs are exposed.
✅ Closes: #837
Loom explaining change: https://www.loom.com/share/a93303a5e3b54038b4fe8c260d0105e8
> chore: 🤖 Fix storybook documentation scroll

- package-lock.json
Saw that there was an error when running `npm ci`
This should sort that out. 
```
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
```
> chore: 🤖 gets the package lock in sync with package.json

- src/components/SQForm/SQForm.tsx
✅ Closes: 842
loom: https://www.loom.com/share/b3892cb6dafe4874ae4f99ac8ba4173f
adds a way to provide props to formik's Form element inside of SQForm.
> feat: 🎸 Adds formProps to SQForm to allow overrides

- src/components/SQForm/useForm.tsx
Fixes the `<p> cannot appear as a descendant of <p>` console error that appears in dev console and during tests.
✅ Closes: #838
> fix: 🐛 HelperText console error

- src/components/fields/SQFormMasked/SQFormMaskedReadOnlyField.tsx
Update the current implementation of the Masked Read Only Field with added specifications. Here is the current implementation of this SQForm: https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformmaskedreadonlyfield--default  (this is an example link)
Design reference: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678 
Typography: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946 
Color: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646 
Default:
Label:  Text Style: Label 12 px Weight: 400
Loom Demo: [here](https://www.loom.com/share/309a383180244435b6b4e3e2327c9f2el)
> SSR-163: SQForms: Masked Read Only Field - Update component

- src/components/fields/SQFormMasked/SQFormMaskedTextField.tsx
Update the current implementation of the Masked Text Field with added specifications. Here is the current implementation of this SQForm: [Webpack App](https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformmaskedtextfield--default)  (this is an example link)
Design reference: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678) 
Typography: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946) 
Color: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646) 
Default:
Label:  Text Style: Label 12 px Weight: 400
Screenshot
> feat: 🎸 Update SQForm Masked TextField

- src/components/fields/SQFormMultiSelect/SQFormMultiSelect.tsx
Update the current implementation of the MultiSelect with added specifications. Here is the current implementation of this SQForm: [Webpack App](https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformmultiselect--sq-form-multi-select)    (this is an example link)
Design reference: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678) 
Typography: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946) 
Color: [SC3 DESIGN LIBRARY](https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646) 
Default:
Label:  Text Style: Label 12 px Weight: 400
Screenshots:
Updated font …
> feat: 🎸 Update Component Multi-Select

- stories/__tests__/SQFormDatePicker.stories.test.tsx
Changes in this PR are mainly due to VSCode react-testing-library intellisense suggestions.  There is still an ongoing "issue" with the datepicker tests where the input and calendar button seem to be treated as one input with the role of `textbox`.  Due to the fact that this seems to be controlled by MUI, it may not be doable to alter this on our end.  See discussion on the issue if interested https://github.com/SelectQuoteLabs/SQForm/issues/876.
✅ Closes: #876
> test: 💍 Update DatePicker tests

- release.config.js
- src/components/SQForm/SQFormMultiSelect.tsx
- stories/SQForm.stories.tsx
Added the ability for the SQFormMultiselect to be virtualized. This GREATLY improves performance for implementations with a lot of options. Kept the virtualization optional to avoid breaking changes within v9.
This will look to release v9.8.0, I'm fairly certain. I will then merge this feature into master as well.
Loom: https://www.loom.com/share/20e25bd99e0148d88a4c5bcdd545331b
> feat: 🎸 Virtualized Multiselect

- .github/workflows/CI.yml
- .github/workflows/Publish.yml
- .github/workflows/Storybook.yml
- release.config.js
Modified github actions to allow for maintenance releases. Will only trigger on the master branch and branches that contain the string `maintenance-release`
> Adjust Github actions for maintenance releases

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/SQFormTransferProductPanels.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/Step.tsx
- src/components/SQFormTransferTool/types.ts
- src/components/SQFormTransferTool/util.tsx
- stories/SQFormTransferTool.stories.tsx
The loom tells almost all https://www.loom.com/share/3bbf5a8effff4f4a98d5ad6cea23ba7c?sid=800f3080-1a3e-41bd-a1ea-20e1c7365337
Additionally: 
1. the spacing issue I mention is resolved on epic/version-11, it is an issue with dropdown that is fixed.
2. The data contract on transfer is a bit shaky. Please review it a bit extra. Since this is going to be just between the consumer and this component we have some flex on how to make it work. There was not a strict requirement provided.
Here is the screen shot of the data being logged out to the console on transfer click: 
and on save / close (more work for this on the next PR)
> SC3-1811 transfer step

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/DialogInner.tsx
- src/components/SQFormTransferTool/SQFormTransferProductPanels.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/Step.tsx
- src/components/SQFormTransferTool/types.ts
- src/components/SQFormTransferTool/util.tsx
- stories/SQFormTransferTool.stories.tsx
Once again the loom is very informative:[ Informative Loom ](https://www.loom.com/share/73851796b63b41d686ad44a7f2d6ca97?sid=08b518cc-7f41-4541-920c-9f30882add94)
Adds to both onSave and onTransfer Callbacks a list of ids for products whose panels were opened ([watch the loom](https://www.loom.com/share/73851796b63b41d686ad44a7f2d6ca97?sid=08b518cc-7f41-4541-920c-9f30882add94)).
[Thanks](https://www.loom.com/share/73851796b63b41d686ad44a7f2d6ca97?sid=08b518cc-7f41-4541-920c-9f30882add94)
**NOTE: The loom didn't capture the console. I will be evaluating and getting that info to this somehow. Either a new loom or an addendum**
> feat: 🎸 adds the viewed products ids to callbacks

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/SQFormTransferTool.tsx
- src/components/SQFormTransferTool/types.ts
- src/index.ts
- stories/SQFormTransferTool.stories.tsx
Loom should tell all https://www.loom.com/share/fb1ba4d5ceac4bf2afc43af3e9f754d6?sid=bda677b3-78e3-4150-9486-8d6e9019dbc1
Some basic clean up from consuming on the branch `epic/mui5` for senior. 
Added formik helpers to the callbacks so that we can reset the form (to avoid the conditional rendering of modals, unless that is your bag, then that works too).
Also added a prop for overriding the loading message.
> SC3-1863 formik helpers & loading msg

- .gitignore
- src/components/fields/SQFormDatePicker/SQFormDatePickerWithDateFNS.tsx
- src/components/fields/SQFormDatePicker/SQFormDateTimePicker.tsx
✅ Closes: #918
tested both in storybook and as a package in sc2-senior (my epic/mui5 branch).
The error did not show.
> fix: 🐛 DateTimePicker consumer would get an error due to incorrect import

- src/components/SQFormDialog/SQFormDialogInner.tsx
Fields were going behind from modal header
When viewing a form modal, when you scroll a list of fields, the fields are scrolling on top of the header section.
AC:
When you scroll on a form modal the fields do not show in the header
Loom: https://www.loom.com/share/cc4810764e18427190b28f9cb84317d2?sid=900f374e-e0a9-405b-8363-303fec387d8a
✅ Closes: #920
> fix: 🐛 Fields scroll behind form modal header

- src/components/SQFormTransferTool/AccordionBody.tsx
- src/components/SQFormTransferTool/Step.tsx
- src/components/SQFormTransferTool/types.ts
- src/components/SQFormTransferTool/util.tsx
- stories/SQFormTransferTool.stories.tsx
Sorry for the scratchy audio, I think I had a postit note on my mic. 
Anyway, small change due to a data shape change. 
https://www.loom.com/share/218505b4b9704859885074b7c38707a4?sid=3c87aca2-d24a-49d6-b32d-f0b33ddc3707
> fix: 🐛 the data contract changed, we need `script` instead
